# Build worker image (VM template)
build: off

# clone directory
clone_folder: C:\Users\appveyor\go\src\github.com\aliyun\aliyun-cli

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - cmd: git submodule update --init --recursive
  - cmd: set path=%path%;C:\Users\appveyor\go\bin
  - cmd: set VERSION=3.0.86
  - cmd: go get -u github.com/shuLhan/go-bindata/...  
  - cmd: go-bindata -o resource/metas.go -pkg resource ./aliyun-openapi-meta/...
  - cmd: go build -ldflags "-X 'github.com/aliyun/aliyun-cli/cli.Version=%VERSION%'" -o C:\Users\appveyor\go\bin\aliyun.exe main/main.go

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

test_script:
- ps: >-
    go vet ./cli/... ./config/... ./i18n/... ./main/... ./openapi/... ./oss/... ./resource/...

    go test -covermode=atomic ./cli/... ./config/... ./i18n/... ./meta/... ./main/... ./openapi/... ./resource/...

    $client = new-object System.Net.WebClient

    $client.DownloadFile('https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe', 'C:/go/bin/jq.exe')

    if (-not $env:ACCESS_KEY_ID.length -eq 0 -and -not $env:ACCESS_KEY_SECRET.length -eq 0){./integration/ecs_test.PS1}
