# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  branch = "master"

[[constraint]]
  name = "github.com/aliyun/aliyun-oss-go-sdk"
  version = "1.8.0"

[[constraint]]
  name = "github.com/aliyun/ossutil"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/alyu/configparser"

[[constraint]]
  branch = "master"
  name = "github.com/droundy/goopt"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  version = "0.2.2"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/posener/complete"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "1.36.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
